import { ulid } from "@/lib/rfq/ulid";
import { isOdooSyncEvent, type OdooSyncEvent } from "@/lib/queue/types";
import { postRfqToOdoo } from "@/lib/odoo/rfq-api-client";
import { buildOutboundRfqIdempotencyKey, mapRfqToApiPayload, type RfqSnapshotForMapping, type RfqSnapshotItem } from "@/lib/odoo/rfq-payload-mapper";
import type { RfqApiOutcome } from "@/lib/odoo/rfq-api-types";

// D1Database is a global ambient type from worker-configuration.d.ts (generated by `wrangler types`) — no import needed.

/**
 * Odoo-sync queue consumer — 01-sources/TECHNICAL_ARCHITECTURE.md §12.3/§14.4,
 * docs/ODOO_RFQ_API_INTEGRATION.md.
 *
 * Delivers to the canonical Odoo Public RFQ Intake API v1 (`POST
 * /api/v1/rfq`, docs/integrations/odoo/rfq-v1/RFQ_API_CONTRACT_V1.md,
 * DOCUMENT_AUDIT_REPORT.md DAR-041) — never the legacy generic-ORM
 * `crm.lead` path (`lib/odoo/adapter.ts`, now deprecated for RFQ delivery;
 * still used by nothing else, kept only for historical readability, see its
 * own file header). `ahanassa.rfq`/`ahanassa.rfq.line` creation is the only
 * Odoo side effect of this consumer; CRM opportunity creation is a private,
 * operator/qualification-gated Odoo-side workflow downstream of that, never
 * triggered from here.
 *
 * Cloudflare Queues is at-least-once; every step here is written to be safe
 * under repeated delivery of the same message:
 *
 * - `rfqs.odoo_rfq_reference IS NOT NULL` is checked before ever calling
 *   Odoo — an already-synced RFQ is never re-sent (idempotent no-op).
 * - The outbound `Idempotency-Key` is deterministic
 *   (`buildOutboundRfqIdempotencyKey(rfq.id)`) and unchanged across every
 *   retry of the same RFQ, so even a Queue-level redelivery that races past
 *   the D1 check above lands on Odoo's own idempotent-replay behavior
 *   (200, `meta.idempotent_replay: true`) rather than a duplicate
 *   `ahanassa.rfq` record.
 * - The outbound payload is built only from already-persisted, immutable
 *   D1 `rfqs`/`rfq_contacts`/`rfq_items` rows (`lib/odoo/rfq-payload-mapper.ts`)
 *   — never from live/mutable Catalog data — so a retry's payload is
 *   byte-for-byte identical to the original attempt's, satisfying Odoo's
 *   same-key-same-payload safe-replay contract.
 */
export interface QueueConsumerEnv {
  DB_OPS?: D1Database;
}

export interface QueueMessageLike {
  id: string;
  body: unknown;
  attempts: number;
  retry: () => void;
  ack: () => void;
}

export interface QueueBatchLike {
  queue: string;
  messages: QueueMessageLike[];
}

export async function handleOdooSyncBatch(batch: QueueBatchLike, env: QueueConsumerEnv): Promise<void> {
  const db = env.DB_OPS;
  if (!db) {
    // No DB binding in this environment — nothing safe to do; leave
    // messages for redelivery rather than silently dropping them.
    for (const message of batch.messages) message.retry();
    return;
  }

  if (batch.queue.endsWith("-dlq")) {
    for (const message of batch.messages) {
      await recordDeadLetter(db, message);
      message.ack();
    }
    return;
  }

  for (const message of batch.messages) {
    try {
      await processMessage(db, message);
      message.ack();
    } catch {
      // Transient failure — let Cloudflare Queues' configured retry policy
      // and eventual DLQ handle it; never swallow the failure as success.
      message.retry();
    }
  }
}

async function processMessage(db: D1Database, message: QueueMessageLike): Promise<void> {
  if (!isOdooSyncEvent(message.body)) {
    // Unrecognized/older schema version — do not retry forever; record and ack.
    await db
      .prepare(
        `INSERT INTO dead_letter_records (id, event_id, failure_category, retry_count, first_failed_at, last_failed_at, resolution_status, raw_message_json)
         VALUES (?, NULL, 'unrecognized_message_schema', ?, ?, ?, 'open', ?)`,
      )
      .bind(ulid(), message.attempts, new Date().toISOString(), new Date().toISOString(), safeSerialize(message.body))
      .run();
    message.ack();
    return;
  }

  const event = message.body;
  const startedAt = new Date().toISOString();

  const rfq = await db
    .prepare(
      `SELECT r.id, r.odoo_rfq_reference, r.company_name, r.message, r.locale, c.full_name, c.email_normalized, c.phone_national
       FROM rfqs r JOIN rfq_contacts c ON c.rfq_id = r.id
       WHERE r.id = ?`,
    )
    .bind(event.aggregate_id)
    .first<{
      id: string;
      odoo_rfq_reference: string | null;
      company_name: string | null;
      message: string | null;
      locale: string;
      full_name: string;
      email_normalized: string | null;
      phone_national: string | null;
    }>();

  if (!rfq) {
    // RFQ row missing (should not happen given the transactional outbox write) —
    // not retryable; record for operator review rather than looping forever.
    await recordAttempt(db, event, startedAt, "permanent_failure", "RFQ_NOT_FOUND");
    await markSyncStatus(db, event.aggregate_id, "failed", "RFQ_NOT_FOUND");
    return;
  }

  if (rfq.odoo_rfq_reference) {
    // Already synced by a prior delivery of this (or an equivalent) event — idempotent no-op.
    await recordAttempt(db, event, startedAt, "success", null);
    return;
  }

  const itemRows = await db
    .prepare(
      `SELECT line_number, variant_ref, sku_snapshot, freeform_title, description, quantity_text, quantity_value, quantity_scale, unit_ref
       FROM rfq_items WHERE rfq_id = ? ORDER BY line_number ASC`,
    )
    .bind(event.aggregate_id)
    .all<{
      line_number: number;
      variant_ref: string | null;
      sku_snapshot: string | null;
      freeform_title: string | null;
      description: string | null;
      quantity_text: string;
      quantity_value: number | null;
      quantity_scale: number | null;
      unit_ref: string | null;
    }>();

  const items: RfqSnapshotItem[] = (itemRows.results ?? []).map((item) => ({
    lineNumber: item.line_number,
    variantRef: item.variant_ref,
    skuSnapshot: item.sku_snapshot,
    freeformTitle: item.freeform_title,
    description: item.description,
    quantityText: item.quantity_text,
    quantityValue: item.quantity_value,
    quantityScale: item.quantity_scale,
    unitCode: item.unit_ref,
  }));

  const snapshot: RfqSnapshotForMapping = {
    locale: rfq.locale,
    fullName: rfq.full_name,
    companyName: rfq.company_name,
    phone: rfq.phone_national,
    email: rfq.email_normalized,
    message: rfq.message,
    items,
  };

  const mapping = mapRfqToApiPayload(snapshot);
  if (!mapping.ok) {
    // A real, non-fabricating blocker (unconvertible quantity/unresolved
    // UoM/missing free-text description/unsupported locale/no items) —
    // never guessed around. Terminal: retrying without a data fix would
    // reproduce the identical blocker, so this is manual_review, not a
    // Queue-retried transient failure. See lib/odoo/rfq-payload-mapper.ts.
    const reasonCode = `RFQ_MAPPING_${mapping.reason}`;
    await markSyncStatus(db, event.aggregate_id, "manual_review", reasonCode);
    await recordAttempt(db, event, startedAt, "permanent_failure", reasonCode);
    return;
  }

  await markSyncStatus(db, event.aggregate_id, "syncing", null);

  const idempotencyKey = buildOutboundRfqIdempotencyKey(rfq.id);
  const outcome = await postRfqToOdoo(mapping.payload, idempotencyKey);

  // verification_session (when present on `outcome.status === "created"`) is
  // deliberately never read past this point — not logged, not persisted, not
  // forwarded to recordAttempt/markSyncStatus. See docs/ODOO_RFQ_API_INTEGRATION.md
  // "verification_session boundary".

  if (outcome.status === "created" || outcome.status === "replayed") {
    const written = await persistOdooRfqReference(db, event.aggregate_id, outcome.reference);
    if (!written) {
      // The unique index on rfqs.odoo_rfq_reference rejected the write —
      // some other local RFQ already holds this exact Odoo reference. This
      // should be structurally unreachable (each Website RFQ maps to its
      // own deterministic Idempotency-Key), so fail closed and flag for
      // operator review rather than silently overwriting or retrying.
      await markSyncStatus(db, event.aggregate_id, "manual_review", "ODOO_RFQ_REFERENCE_COLLISION");
      await recordAttempt(db, event, startedAt, "permanent_failure", "ODOO_RFQ_REFERENCE_COLLISION");
      return;
    }
    await recordAttempt(db, event, startedAt, "success", null);
    return;
  }

  const classification = classifyOutcome(outcome);
  await markSyncStatus(db, event.aggregate_id, classification.syncStatus, outcome.reasonCode);
  await recordAttempt(db, event, startedAt, classification.attemptOutcome, outcome.reasonCode);

  if (classification.retryable) {
    // Only a real transient failure should trigger queue-level redelivery.
    throw new Error(`odoo_rfq_sync_${outcome.status}`);
  }
}

/**
 * Stage F error classification — docs/ODOO_RFQ_API_INTEGRATION.md.
 * 400/409/413/415 terminal (manual review); 401 terminal (credential/config
 * failure — never blindly retried indefinitely); `not_configured` mirrors
 * the pre-existing "pending, not failed" convention (an expected, stable
 * state until Deployment Stage 1 provisions the secret); 500/network/
 * malformed-response are retryable under the existing Queue policy, using
 * the SAME outbound Idempotency-Key on every retry.
 */
type OdooRfqSyncFailureOutcome = Exclude<RfqApiOutcome, { status: "created" } | { status: "replayed" }>;

function classifyOutcome(outcome: OdooRfqSyncFailureOutcome): { syncStatus: "pending" | "retry" | "failed" | "manual_review"; attemptOutcome: "transient_failure" | "permanent_failure"; retryable: boolean } {
  switch (outcome.status) {
    case "not_configured":
      return { syncStatus: "pending", attemptOutcome: "permanent_failure", retryable: false };
    case "server_error":
    case "network_error":
    case "malformed_response":
      return { syncStatus: "retry", attemptOutcome: "transient_failure", retryable: true };
    case "invalid_payload":
    case "idempotency_conflict":
    case "payload_too_large":
    case "unsupported_media_type":
      return { syncStatus: "manual_review", attemptOutcome: "permanent_failure", retryable: false };
    case "unauthorized":
      return { syncStatus: "failed", attemptOutcome: "permanent_failure", retryable: false };
  }
}

async function persistOdooRfqReference(db: D1Database, rfqId: string, reference: string): Promise<boolean> {
  try {
    await db
      .prepare(`UPDATE rfqs SET sync_status = 'synced', odoo_rfq_reference = ?, last_synced_at = ?, updated_at = ? WHERE id = ?`)
      .bind(reference, new Date().toISOString(), new Date().toISOString(), rfqId)
      .run();
    return true;
  } catch {
    return false;
  }
}

async function markSyncStatus(db: D1Database, rfqId: string, status: string, errorCode: string | null): Promise<void> {
  await db
    .prepare(`UPDATE rfqs SET sync_status = ?, last_sync_error_code = ?, updated_at = ? WHERE id = ?`)
    .bind(status, errorCode, new Date().toISOString(), rfqId)
    .run();
}

async function recordAttempt(
  db: D1Database,
  event: OdooSyncEvent,
  startedAt: string,
  outcome: "success" | "transient_failure" | "permanent_failure",
  errorCode: string | null,
): Promise<void> {
  await db
    .prepare(
      `INSERT INTO integration_attempts (id, event_id, provider, attempt_number, started_at, finished_at, http_status_category, outcome, error_code, correlation_id)
       VALUES (?, ?, 'odoo', (SELECT COALESCE(MAX(attempt_number), 0) + 1 FROM integration_attempts WHERE event_id = ?), ?, ?, NULL, ?, ?, ?)`,
    )
    .bind(ulid(), event.event_id, event.event_id, startedAt, new Date().toISOString(), outcome, errorCode, event.correlation_id)
    .run();
}

async function recordDeadLetter(db: D1Database, message: QueueMessageLike): Promise<void> {
  const now = new Date().toISOString();
  const eventId = isOdooSyncEvent(message.body) ? message.body.event_id : null;
  const aggregateId = isOdooSyncEvent(message.body) ? message.body.aggregate_id : null;
  await db
    .prepare(
      `INSERT INTO dead_letter_records (id, event_id, aggregate_type, aggregate_id, failure_category, retry_count, first_failed_at, last_failed_at, resolution_status, raw_message_json)
       VALUES (?, ?, 'rfq', ?, 'retries_exhausted', ?, ?, ?, 'open', ?)`,
    )
    .bind(ulid(), eventId, aggregateId, message.attempts, now, now, safeSerialize(message.body))
    .run();
}

function safeSerialize(value: unknown): string {
  try {
    // Queue message bodies here are event envelopes (identifiers only, no
    // PII/secrets by contract — lib/queue/outbox.ts) so this is safe to
    // store for operator replay.
    return JSON.stringify(value).slice(0, 4000);
  } catch {
    return "unserializable";
  }
}
