import { ulid } from "@/lib/rfq/ulid";
import { isOdooSyncEvent, type OdooSyncEvent } from "@/lib/queue/types";
import { createOdooAdapter } from "@/lib/odoo/adapter";

// D1Database is a global ambient type from worker-configuration.d.ts (generated by `wrangler types`) — no import needed.

/**
 * Odoo-sync queue consumer — 01-sources/TECHNICAL_ARCHITECTURE.md §12.3/§14.4.
 * Cloudflare Queues is at-least-once; every step here is written to be safe
 * under repeated delivery of the same message:
 *
 * - `integration_mappings` is checked before calling Odoo — an existing
 *   mapping for this RFQ means it was already synced, so the adapter is
 *   never called again for it (never creates a duplicate lead/RFQ).
 * - Odoo credentials/mapping are unresolved in this phase (DAR-013), so
 *   the adapter always returns `not_configured` — the RFQ is left in
 *   `sync_status = 'pending'` rather than falsely marked `synced` or
 *   `failed`. It is exercised end-to-end today so the moment the mapping
 *   is approved, only lib/odoo/adapter.ts changes.
 */
export interface QueueConsumerEnv {
  DB_OPS?: D1Database;
}

export interface QueueMessageLike {
  id: string;
  body: unknown;
  attempts: number;
  retry: () => void;
  ack: () => void;
}

export interface QueueBatchLike {
  queue: string;
  messages: QueueMessageLike[];
}

export async function handleOdooSyncBatch(batch: QueueBatchLike, env: QueueConsumerEnv): Promise<void> {
  const db = env.DB_OPS;
  if (!db) {
    // No DB binding in this environment — nothing safe to do; leave
    // messages for redelivery rather than silently dropping them.
    for (const message of batch.messages) message.retry();
    return;
  }

  if (batch.queue.endsWith("-dlq")) {
    for (const message of batch.messages) {
      await recordDeadLetter(db, message);
      message.ack();
    }
    return;
  }

  for (const message of batch.messages) {
    try {
      await processMessage(db, message);
      message.ack();
    } catch {
      // Transient failure — let Cloudflare Queues' configured retry policy
      // and eventual DLQ handle it; never swallow the failure as success.
      message.retry();
    }
  }
}

async function processMessage(db: D1Database, message: QueueMessageLike): Promise<void> {
  if (!isOdooSyncEvent(message.body)) {
    // Unrecognized/older schema version — do not retry forever; record and ack.
    await db
      .prepare(
        `INSERT INTO dead_letter_records (id, event_id, failure_category, retry_count, first_failed_at, last_failed_at, resolution_status, raw_message_json)
         VALUES (?, NULL, 'unrecognized_message_schema', ?, ?, ?, 'open', ?)`,
      )
      .bind(ulid(), message.attempts, new Date().toISOString(), new Date().toISOString(), safeSerialize(message.body))
      .run();
    message.ack();
    return;
  }

  const event = message.body;
  const startedAt = new Date().toISOString();

  const existingMapping = await db
    .prepare(`SELECT remote_model, remote_id FROM integration_mappings WHERE provider = 'odoo' AND local_entity_type = 'rfq' AND local_entity_id = ?`)
    .bind(event.aggregate_id)
    .first<{ remote_model: string; remote_id: number }>();

  if (existingMapping) {
    // Already synced by a prior delivery of this (or an equivalent) event — idempotent no-op.
    await recordAttempt(db, event, startedAt, "success", null);
    return;
  }

  const rfq = await db
    .prepare(
      `SELECT r.id, r.reference_number, r.company_name, r.message, r.locale, c.full_name, c.email_normalized, c.phone_national
       FROM rfqs r JOIN rfq_contacts c ON c.rfq_id = r.id
       WHERE r.id = ?`,
    )
    .bind(event.aggregate_id)
    .first<{
      id: string;
      reference_number: string;
      company_name: string | null;
      message: string | null;
      locale: string;
      full_name: string;
      email_normalized: string | null;
      phone_national: string | null;
    }>();

  if (!rfq) {
    // RFQ row missing (should not happen given the transactional outbox write) —
    // not retryable; record for operator review rather than looping forever.
    await recordAttempt(db, event, startedAt, "permanent_failure", "RFQ_NOT_FOUND");
    await markSyncStatus(db, event.aggregate_id, "failed", "RFQ_NOT_FOUND");
    return;
  }

  const items = await db
    .prepare(`SELECT product_label, freeform_title, quantity_text, description FROM rfq_items WHERE rfq_id = ? ORDER BY line_number ASC`)
    .bind(event.aggregate_id)
    .all<{ product_label: string | null; freeform_title: string | null; quantity_text: string; description: string | null }>();

  await markSyncStatus(db, event.aggregate_id, "syncing", null);

  const adapter = createOdooAdapter();
  const result = await adapter.upsertRfq({
    localRfqId: rfq.id,
    referenceNumber: rfq.reference_number,
    contact: {
      fullName: rfq.full_name,
      companyName: rfq.company_name,
      email: rfq.email_normalized,
      phone: rfq.phone_national,
    },
    items: (items.results ?? []).map((item) => ({
      label: item.product_label ?? item.freeform_title ?? "",
      quantityText: item.quantity_text,
      description: item.description,
    })),
    message: rfq.message,
    locale: rfq.locale,
    correlationId: event.correlation_id,
  });

  if (result.status === "synced" && result.lead) {
    await db.batch([
      db
        .prepare(
          `INSERT INTO integration_mappings (id, provider, local_entity_type, local_entity_id, remote_model, remote_id, sync_version, last_success_at)
           VALUES (?, 'odoo', 'rfq', ?, ?, ?, 1, ?)`,
        )
        .bind(ulid(), event.aggregate_id, result.lead.model, result.lead.id, new Date().toISOString()),
      db
        .prepare(`UPDATE rfqs SET sync_status = 'synced', odoo_lead_id = ?, last_synced_at = ?, updated_at = ? WHERE id = ?`)
        .bind(result.lead.id, new Date().toISOString(), new Date().toISOString(), event.aggregate_id),
    ]);
    await recordAttempt(db, event, startedAt, "success", null);
    return;
  }

  // not_configured or failed: RFQ stays durably `pending`/`retry` in D1 —
  // never falsely marked synced. See file header.
  const reasonCode = result.reasonCode ?? "UNKNOWN";
  const nextStatus = result.status === "not_configured" ? "pending" : "retry";
  await markSyncStatus(db, event.aggregate_id, nextStatus, reasonCode);
  await recordAttempt(db, event, startedAt, result.status === "not_configured" ? "permanent_failure" : "transient_failure", reasonCode);

  if (result.status !== "not_configured") {
    // Only a real transient failure should trigger queue-level redelivery;
    // "not configured" is an expected, stable state in this phase.
    throw new Error(`odoo_sync_${result.status}`);
  }
}

async function markSyncStatus(db: D1Database, rfqId: string, status: string, errorCode: string | null): Promise<void> {
  await db
    .prepare(`UPDATE rfqs SET sync_status = ?, last_sync_error_code = ?, updated_at = ? WHERE id = ?`)
    .bind(status, errorCode, new Date().toISOString(), rfqId)
    .run();
}

async function recordAttempt(
  db: D1Database,
  event: OdooSyncEvent,
  startedAt: string,
  outcome: "success" | "transient_failure" | "permanent_failure",
  errorCode: string | null,
): Promise<void> {
  await db
    .prepare(
      `INSERT INTO integration_attempts (id, event_id, provider, attempt_number, started_at, finished_at, http_status_category, outcome, error_code, correlation_id)
       VALUES (?, ?, 'odoo', (SELECT COALESCE(MAX(attempt_number), 0) + 1 FROM integration_attempts WHERE event_id = ?), ?, ?, NULL, ?, ?, ?)`,
    )
    .bind(ulid(), event.event_id, event.event_id, startedAt, new Date().toISOString(), outcome, errorCode, event.correlation_id)
    .run();
}

async function recordDeadLetter(db: D1Database, message: QueueMessageLike): Promise<void> {
  const now = new Date().toISOString();
  const eventId = isOdooSyncEvent(message.body) ? message.body.event_id : null;
  const aggregateId = isOdooSyncEvent(message.body) ? message.body.aggregate_id : null;
  await db
    .prepare(
      `INSERT INTO dead_letter_records (id, event_id, aggregate_type, aggregate_id, failure_category, retry_count, first_failed_at, last_failed_at, resolution_status, raw_message_json)
       VALUES (?, ?, 'rfq', ?, 'retries_exhausted', ?, ?, ?, 'open', ?)`,
    )
    .bind(ulid(), eventId, aggregateId, message.attempts, now, now, safeSerialize(message.body))
    .run();
}

function safeSerialize(value: unknown): string {
  try {
    // Queue message bodies here are event envelopes (identifiers only, no
    // PII/secrets by contract — lib/queue/outbox.ts) so this is safe to
    // store for operator replay.
    return JSON.stringify(value).slice(0, 4000);
  } catch {
    return "unserializable";
  }
}
